secrets:
  db_password:
    environment: "DbPassword"

services:
  libmgr-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: "/c/Users/an/Documents/Projects/BLibMgr/src/Api/UploadedDocs"
        target: "/App/UploadedDocs"
    environment:
      - DbPassword=/run/secrets/db_password
      - Cors__AllowedOrigins=${CorsAllowedOrigins}
    secrets:
      - db_password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  libmgr-client:
    depends_on:
      - libmgr-server
    build: ./web
    ports:
      - "4200:80"
