secrets:
  db_password:
    environment: "DbPassword"
  merriam_webster_api_key:
    environment: "MerriamWebster__ApiKey"

services:
  libmgr-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: "${KeysPath}"
        target: "/app/Keys"
      - type: bind
        source: "${StoragePath}"
        target: "/app/UploadedDocs"
    environment:
      DbUser: ${DbUser}
      DbPasswordFile: /run/secrets/db_password
      Cors__AllowedOrigins: ${CorsAllowedOrigins}
      YandexCloud__KeyId: ${YandexCloud__KeyId}
      YandexCloud__ServiceAccountId: ${YandexCloud__ServiceAccountId}
      YandexCloud__FolderPath: ${YandexCloud__FolderPath}
      MerriamWebster__ApiKeyFile: /run/secrets/merriam_webster_api_key
    secrets:
      - db_password
      - merriam_webster_api_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  libmgr-client:
    depends_on:
      - libmgr-server
    build: ./web
    ports:
      - "4200:80"
