secrets:
  db_password:
    environment: "DbPassword"
  merriam_webster_api_key:
    environment: "MerriamWebster__ApiKey"

services:
  server:
    container_name: libmgr-server
    image: "registry.rpi5.lan/an/blibmgr/libmgr-server:latest"
    build:
      context: .
      network: host
      tags:
        - "libmgr-server:latest"
        - "registry.rpi5.lan/an/blibmgr/libmgr-server:latest"
    ports:
      - "10080:8080"
    volumes:
      - type: bind
        source: "${KeysPath}"
        target: "/app/Keys"
      - type: bind
        source: "${StoragePath}"
        target: "/app/UploadedDocs"
    environment:
      DbUser: ${DbUser}
      DbPasswordFile: /run/secrets/db_password
      Cors__AllowedOrigins: ${CorsAllowedOrigins}
      YandexCloud__KeyId: ${YandexCloud__KeyId}
      YandexCloud__ServiceAccountId: ${YandexCloud__ServiceAccountId}
      YandexCloud__FolderPath: ${YandexCloud__FolderPath}
      MerriamWebster__ApiKeyFile: /run/secrets/merriam_webster_api_key
    secrets:
      - db_password
      - merriam_webster_api_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    container_name: libmgr-client
    image: "registry.rpi5.lan/an/blibmgr/libmgr-client:latest"
    depends_on:
      - server
    build:
      context: ./web
      network: host
      tags:
        - "libmgr-client:latest"
        - "registry.rpi5.lan/an/blibmgr/libmgr-client:latest"
    ports:
      - "4200:80"
