/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BookManager.Domain.Enums.BookFileType */
export enum BookFileType {
    Pdf = 0,
    Epub = 1,
}

