/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { BookFileType } from './BookManager.Domain.Enums';

/** Transpiled from BookManager.Application.Common.DTOs.AddUserRequest */
export type AddUserRequest = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    pinCode: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto */
export type BookDto = {
    /** Transpiled from BookManager.Application.Common.DTOs.BookDto.Details */
    documentDetails: Details;
    /** Transpiled from BookManager.Application.Common.DTOs.BookDto.BookFileMetadata */
    fileMetadata: BookFileMetadata;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto.Details */
export type Details = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    isbn?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from string? */
    publisherName?: string;
    /** Transpiled from byte[]? */
    thumbnail?: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto.BookFileMetadata */
export type BookFileMetadata = {
    /** Transpiled from BookManager.Domain.Enums.BookFileType */
    type: BookFileType;
    /** Transpiled from long */
    size: number;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookMetadataDto */
export type BookMetadataDto = {
    /** Transpiled from string */
    filename: string;
    /** Transpiled from long */
    fileSizeInBytes: number;
    /** Transpiled from BookManager.Domain.Enums.BookFileType */
    fileType: BookFileType;
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    isbn?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from string? */
    publisherName?: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.UserDto */
export type UserDto = {
    /** Transpiled from string */
    name: string;
}

