/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { BookFileType } from './BookManager.Domain.Enums';

/** Transpiled from BookManager.Application.Common.DTOs.AuthenticationRequestDto */
export type AuthenticationRequestDto = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    pinCode: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.AuthenticationResponseDto */
export type AuthenticationResponseDto = {
    /** Transpiled from BookManager.Application.Common.DTOs.AuthenticationStatus */
    status: AuthenticationStatus;
    /** Transpiled from string? */
    accessToken?: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.AuthenticationStatus */
export enum AuthenticationStatus {
    Failed = 0,
    Success = 1,
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDetailsUpdateDto */
export type BookDetailsUpdateDto = {
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto */
export type BookDto = {
    /** Transpiled from BookManager.Application.Common.DTOs.BookDto.Details */
    documentDetails: Details;
    /** Transpiled from BookManager.Application.Common.DTOs.BookDto.BookFileMetadata */
    fileMetadata: BookFileMetadata;
    /** Transpiled from BookManager.Application.Common.DTOs.BookDto.UserStats? */
    stats?: UserStats;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto.Details */
export type Details = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    isbn?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from string? */
    publisherName?: string;
    /** Transpiled from string? */
    thumbnailUrl?: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto.UserStats */
export type UserStats = {
    /** Transpiled from long */
    totalReadingTime: number;
    /** Transpiled from System.DateTimeOffset */
    recentAccessTime?: (Date | string);
}

/** Transpiled from BookManager.Application.Common.DTOs.BookDto.BookFileMetadata */
export type BookFileMetadata = {
    /** Transpiled from BookManager.Domain.Enums.BookFileType */
    type: BookFileType;
    /** Transpiled from long */
    size: number;
}

/** Transpiled from BookManager.Application.Common.DTOs.BookMetadataDto */
export type BookMetadataDto = {
    /** Transpiled from string */
    filename: string;
    /** Transpiled from long */
    fileSizeInBytes: number;
    /** Transpiled from BookManager.Domain.Enums.BookFileType */
    fileType: BookFileType;
    /** Transpiled from string? */
    title?: string;
    /** Transpiled from string? */
    isbn?: string;
    /** Transpiled from string? */
    description?: string;
    /** Transpiled from string? */
    publisherName?: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.PageDto<T> */
export type PageDto<T> = {
    /** Transpiled from System.Collections.Generic.IEnumerable<T> */
    items: T[];
    /** Transpiled from int */
    pageSize: number;
    /** Transpiled from int */
    pageNumber: number;
    /** Transpiled from int */
    pageCount: number;
    /** Transpiled from int */
    totalItemCount: number;
}

/** Transpiled from BookManager.Application.Common.DTOs.UserAddRequest */
export type UserAddRequest = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    pinCode: string;
}

/** Transpiled from BookManager.Application.Common.DTOs.UserDto */
export type UserDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
}

